steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "core-model-prediction"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud builds submit \
          --region="us-central1"
          --tag=us-central1-docker.pkg.dev/${PROJECT_ID}/interview-ai-detector/model-prediction

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        MODEL_ID=$(gcloud ai models upload \
          --region="us-central1" \
          --container-ports=8080 \
          --container-image-uri="gcr.io/${PROJECT_ID}/interview-ai-detector/model-prediction:latest" \
          --container-predict-route="/predict" \
          --container-health-route="/health" \
          --display-name="interview-ai-detector-model" \
          --format="value(model)")
        echo "MODEL_ID=${MODEL_ID}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ENDPOINT_ID=$(gcloud ai endpoints create \
          --region="us-central1" \
          --display-name="interview-ai-detector-endpoint" \
          --format="value(name)")
        echo "ENDPOINT_ID=${ENDPOINT_ID}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud ai endpoints deploy-model "${ENDPOINT_ID}" \
          --region="us-central1" \
          --model="${MODEL_ID}" \
          --display-name="interview-ai-detector-deployment" \
          --machine-type="n1-standard-4" \
          --accelerator="count=1,type=nvidia-tesla-t4" \
          --service-account="vertex-ai-user-managed-sa@steady-climate-416810.iam.gserviceaccount.com"
