steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "core-model-prediction"
    args:
      [
        "build",
        "--build-arg",
        "HF_TOKEN=${_HF_TOKEN}",
        "-t",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/interview-ai-detector/model-prediction:latest",
        ".",
      ]
    secretEnv: ["HF_TOKEN"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/interview-ai-detector/model-prediction:latest",
      ]

images:
  - "us-central1-docker.pkg.dev/${PROJECT_ID}/interview-ai-detector/model-prediction:latest"

availableSecrets:
  secretManager:
    - versionName: "projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/1"
      env: "HF_TOKEN"