steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "core-model-prediction"
    entrypoint: "bash"
    secretEnv: ["_HF_TOKEN"]
    args: 
      - -c
      - | 
          docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/interview-ai-detector/model-prediction:latest --build-arg=HF_TOKEN=$$_HF_TOKEN .

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/interview-ai-detector/model-prediction:latest",
      ]

images:
  - "us-central1-docker.pkg.dev/${PROJECT_ID}/interview-ai-detector/model-prediction:latest"

availableSecrets:
  secretManager:
    - versionName: "projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest"
      env: "_HF_TOKEN"